UniversityCoursesAndResultApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCoursesAndResultApp.BLL;
using UniversityCoursesAndResultApp.Models;

namespace UniversityCoursesAndResultApp.Controllers
{
    public class CourseController : Controller
    {
       
        CourseManager courseManager=new CourseManager();
        DepartmentManager departmentManager=new DepartmentManager();
        public ActionResult Save()
        {
            ViewBag.Departments=departmentManager.ViewDepartment();
            ViewBag.Semesters=courseManager.GetAllSemester();
            return View();
        }

        [HttpPost]
        public ActionResult Save(Course course)
        {

                if (courseManager.IsCourseExists(course))
                {
                    ViewBag.ErrorMessage= "Course already Exists";
                }
                else
                {
                    if (course.Credit >= 0.5 && course.Credit <= 5.0)
                    {
                        int rowsAffected = courseManager.SaveCourse(course);

                        if (rowsAffected > 0)
                        {
                            ViewBag.SuccessMessage= "Course inserted Successfully";
                        }
                        else
                        {
                            ViewBag.ErrorMessage= "Insert Failed";
                        }
                    }
                    else
                    {
                       ViewBag.ErrorMessage = "Credit range must be 0.5 to 5.0";
                    }
                }
             ViewBag.Departments=departmentManager.ViewDepartment();
            ViewBag.Semesters=courseManager.GetAllSemester();
            return View();
            }

           
        }


    }

UniversityCoursesAndResultApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCoursesAndResultApp.BLL;
using UniversityCoursesAndResultApp.Models;

namespace UniversityCoursesAndResultApp.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentManager departmentManager = new DepartmentManager();

        public ActionResult SaveDepartment()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult SaveDepartment(Department department)
        {
            
            int codeLength = department.Code.Length;


            bool IsDepartmentExists = departmentManager.IsDepartmentExists(department);

            if (IsDepartmentExists)
            {
                ViewBag.Message = "Department Name or Code Exists";
            }
            else
            {
                if (codeLength >= 2 && codeLength <= 7)
                {
                    var rowAffecetd = departmentManager.SaveDepartment(department);

                    if (rowAffecetd > 0)
                    {
                        ViewBag.Message = "Deparetment Name and Code inserted Successfully";
                    }
                    else
                    {
                        ViewBag.Message = "Insert Failed";
                    }
                }
                else
                {
                   ViewBag.Message = "Code must be two (2) to seven (7) characters long";
                }
            }
            return View();
        }

        public ActionResult ViewDepartment()
        {
            var departments = departmentManager.ViewDepartment();
            ViewBag.departments = departments;
            return View();
        }
       
    }
}

UniversityCoursesAndResultApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityCoursesAndResultApp.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

UniversityCoursesAndResultApp/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCoursesAndResultApp.BLL;
using UniversityCoursesAndResultApp.Models;

namespace UniversityCoursesAndResultApp.Controllers
{
    public class ResultController : Controller
    {
        //
        // GET: /Result/

        DepartmentManager departmentManager = new DepartmentManager();
        RegistrationManager registrationManager = new RegistrationManager();
        CourseManager courseManager = new CourseManager();
        ResultManager resultManager = new ResultManager();
        EnrollStudentManager enrollStudentManager = new EnrollStudentManager();
        ViewResultManager viewResultManager = new ViewResultManager();
        List<ViewResult> resultList = new List<ViewResult>();

        public ActionResult SaveResult()
        {
            ViewBag.StudentList = registrationManager.GetAllStudent();
            ViewBag.DepartmentList = departmentManager.ViewDepartment();
            ViewBag.CourseList = courseManager.GetAllCourses();
            ViewBag.grades = resultManager.GetAllGrades();
            return View();
        }
        [HttpPost]
        public ActionResult SaveResult(Results result)
        {
            
            if (resultManager.IsresultExist(result))
            {
                ViewBag.message = "Results Already Inserted";
            }
            else
            {
                int rowsAffected = resultManager.SaveResult(result);
                if (rowsAffected > 0)
                {
                    ViewBag.message = "Save Successfully";
                }
                else
                {
                    ViewBag.message = "Save Failed";
                }
            }
            ViewBag.StudentList = registrationManager.GetAllStudent();
            ViewBag.DepartmentList = departmentManager.ViewDepartment();
            ViewBag.CourseList = courseManager.GetAllCourses();
            ViewBag.grades = resultManager.GetAllGrades();
            return View();
        }
        public JsonResult GetStudentInfoByStudentId(int studentId)
        {
            var student = registrationManager.GetAllStudent();
            var StudentList = student.Where(m => m.Id == studentId).ToList();

            return Json(StudentList.Select(c => new
            {
                name = c.Name,
                email = c.Email,
                department = departmentManager.ViewDepartment().Where(x => x.Id == c.DepartmentId).Select(x => x.Name).Single()
            }), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCoursesByStudentId(int studentId)
        {
            var aViewResults = enrollStudentManager.GetAllEnrollCourse();
            var selectedCourse = aViewResults.Where(a => a.StudentId == studentId).ToList();
            return Json(selectedCourse, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ViewResult()
        {
            ViewBag.StudentList = registrationManager.GetAllStudent();
            ViewBag.DepartmentList = departmentManager.ViewDepartment();
            return View();
        }

        [HttpPost]
        public ActionResult ViewResult(int? studentId)
        {
            ViewBag.StudentId = registrationManager.GetAllStudent();
            ViewBag.DepartmentList = departmentManager.ViewDepartment();

            if (studentId != null)
            {
                var getStudentById = registrationManager.GetAllStudent().FindAll(s => s.Id == studentId).SingleOrDefault();

                ////Pdf part start
                //// Create a Document object
                //var document = new Document(PageSize.A4, 50, 50, 25, 25);

                //// Create a new PdfWriter object, specifying the output stream
                //var output = new MemoryStream();
                //var writer = PdfWriter.GetInstance(document, output);
                //document.Open();


                //var titleFont = FontFactory.GetFont("Arial", 18, Font.BOLD);
                //var subTitleFont = FontFactory.GetFont("Arial", 14, Font.BOLD);
                //var boldTableFont = FontFactory.GetFont("Arial", 12, Font.BOLD);
                //var endingMessageFont = FontFactory.GetFont("Arial", 10, Font.ITALIC);
                //var bodyFont = FontFactory.GetFont("Arial", 12, Font.NORMAL);

                //document.Add(new Paragraph("UCRMS Result Creator", titleFont));
                //document.Add(new Paragraph("Thank you for using our app for result creating.", bodyFont));
                //document.Add(new Paragraph("Student Results are below", bodyFont));

                //document.Add(Chunk.NEWLINE);

                //document.Add(new Paragraph("Student Information: ", subTitleFont));

                //var studentInfoTable = new PdfPTable(2);
                //studentInfoTable.HorizontalAlignment = 0;
                //studentInfoTable.SpacingBefore = 10;
                //studentInfoTable.SpacingAfter = 10;
                //studentInfoTable.DefaultCell.Border = 0;
                //studentInfoTable.SetWidths(new int[] { 1, 4 });

                //studentInfoTable.AddCell(new Phrase("Student Reg. No.:", boldTableFont));
                //studentInfoTable.AddCell(getStudentById.Registration_Number);
                //studentInfoTable.AddCell(new Phrase("Name :", boldTableFont));
                //studentInfoTable.AddCell(getStudentById.Name);
                //studentInfoTable.AddCell(new Phrase("Email :", boldTableFont));
                //studentInfoTable.AddCell(getStudentById.Email);
                //studentInfoTable.AddCell(new Phrase("Department :", boldTableFont));
                //studentInfoTable.AddCell(departmentManager.ViewDepartment().Where(c => c.Id == getStudentById.DepartmentId).Select(x => x.Name).Single());

                //document.Add(studentInfoTable);

                //document.Add(Chunk.NEWLINE);

                //document.Add(new Paragraph("Result Informatiion: ", subTitleFont));

                //var resultTable = new PdfPTable(3);
                //resultTable.HorizontalAlignment = 1;
                //resultTable.SpacingBefore = 10;
                //resultTable.SpacingAfter = 10;
                //resultTable.TotalWidth = 9f;

                //resultTable.AddCell(new Phrase("Course Code", boldTableFont));
                //resultTable.AddCell(new Phrase("Name", boldTableFont));
                //resultTable.AddCell(new Phrase("Grade", boldTableFont));

                //var Course = viewResultManager.GetAllViewCourse();
                //var courseInfo = Course.Where(m => m.StudentId == studentId).ToList();

                //Models.ViewResult viewResult = new Models.ViewResult();
                //resultTable.AddCell(viewResult.CourseCode);
                //resultTable.AddCell(viewResult.CourseName);
                //resultTable.AddCell(viewResult.Grade);
                //courseInfo.Add(viewResult);

                ////result asbe

                ////resultTable.AddCell();
                //document.Add(resultTable);


                //DateTime dateTime = DateTime.Now;

                //PdfContentByte cb = writer.DirectContent;
                //BaseFont bf = BaseFont.CreateFont(BaseFont.TIMES_ITALIC, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
                //cb.SetFontAndSize(bf, 10);
                //cb.BeginText();
                //cb.SetTextMatrix(50, 5);
                //cb.ShowText(dateTime.ToString());
                //cb.EndText();
                //document.Close();

                //Response.ContentType = "application/pdf";
                //Response.AddHeader("Content-Disposition",
                //    string.Format("attachment;filename=Receipt-{0}.pdf", getStudentById.Registration_Number));
                //Response.BinaryWrite(output.ToArray());
                //ViewBag.message = dateTime.ToString();
                //////pdf ends here
            }
            else
            {
                ViewBag.message = "Fill all field properly";
            }


            return View();
        }

        public JsonResult GetCourseInfoById(int studentId)
        {
            var Course = viewResultManager.GetAllViewCourse();
            var courseInfo = Course.Where(m => m.StudentId == studentId).ToList();
            return Json(courseInfo, JsonRequestBehavior.AllowGet);

        }

    }
}

UniversityCoursesAndResultApp/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCoursesAndResultApp.BLL;
using UniversityCoursesAndResultApp.Models;

namespace UniversityCoursesAndResultApp.Controllers
{
    public class TeacherController : Controller
    {
      TeacherManager teacherManager=new TeacherManager();
        DepartmentManager departmentManager=new DepartmentManager();

        public ActionResult SaveTeacher()
        {
            ViewBag.Departments = departmentManager.ViewDepartment();
            ViewBag.Designation = teacherManager.GetAllDesignation();
            return View();
        }

        [HttpPost]
        public ActionResult SaveTeacher(Teacher teacher)
        {
            if (teacherManager.IsEmailExists(teacher))
            {
                ViewBag.ErrorMessage = "Email already Exists";
            }
            else
            {
                if (teacher.CreditTaken<0)
                {
                    ViewBag.ErrorMessage = "Credit to be taken must contain a non-negative value";
                }
                else
                {
                    teacher.RemainingCredit = teacher.CreditTaken;
                    int rowsAffected = teacherManager.SaveTeacher(teacher);

                    if (rowsAffected > 0)
                    {
                        ViewBag.SuccessMessage = "Teacher inserted Successfully";
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Insert Failed";
                    }
                }
            }
            ViewBag.Departments = departmentManager.ViewDepartment();
            ViewBag.Designation = teacherManager.GetAllDesignation();
            return View();
        }



    }
}

UniversityCoursesAndResultApp/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet"/>
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
<div class="container">
    <h3 class="text-center">University Course and Result Management System</h3><hr/>
    <div class="row">
        <div class="col-md-offset-3 col-md-6">

            <table class="table table-striped">
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("SaveDepartment", "Department")' "><h4>Save Department</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("ViewDepartment", "Department")' "><h4>View Department</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("Save", "Course")' "><h4>Save Course</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("SaveTeacher", "Teacher")' "><h4>Save Teacher</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("AssignCourse", "AssignCourseToTeacher")' "><h4>Course Assign To Teacher</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("CourseStatics", "CourseStatics")' "><h4>View Course Statics</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("RegisterStudent", "StudentRegistration")' "><h4>Register Student</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("AllocateClassroom", "AllocateClassroom")' "><h4>Allocate Classroom</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("ViewAllocatedClass", "AllocateClassroom")' "><h4>Class Schedule and Room Allocation Information</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("EnrollStudent", "StudentRegistration")' "><h4>Enroll in a Course</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("SaveResult", "Result")' "><h4>Save Student Result</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("ViewResult", "Result")' "><h4>View Result</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("UnassignCourse", "UnassignCourse")' "><h4>Unassign All Courses</h4></a></td>

                </tr>
                <tr>

                    <td class="text-center"><a style="color: darkcyan" onclick=" window.location.href = '@Url.Action("UnallocateClassRoom", "UnallocateRoom")' "><h4>Unallocate All Classroom</h4></a></td>

                </tr>
            </table>
        </div>
    </div>

</div>
</body>
</html>