UniversityCoursesAndResultApp/Models/EnrollStudent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityCoursesAndResultApp.Models
{
    public class EnrollStudent
    {
        public int Id { set; get; }
        public int StudentId { set; get; }
        public string StudentName { set; get; }
        public string StudentEmail { set; get; }
        public int CourseId { set; get; }
        public DateTime EnrollDate { set; get; }
        public bool Status { get; set; }    

    }
}

UniversityCoursesAndResultApp/Models/RegisterStudent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityCoursesAndResultApp.Models
{
    public class RegisterStudent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public DateTime Date { get; set; }
        public string Address { get; set; }
        public int DepartmentId { get; set; }
        public string Code { set; get; }
        public string Registration_Number { get; set; }
        public Department department { set; get; }
    }
}

UniversityCoursesAndResultApp/Controllers/StudentRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCoursesAndResultApp.BLL;
using UniversityCoursesAndResultApp.Models;

namespace UniversityCoursesAndResultApp.Controllers
{
    public class StudentRegistrationController : Controller
    {
        DepartmentManager departmentManager = new DepartmentManager();
        RegistrationManager registrationManager = new RegistrationManager();
        CourseManager courseManager = new CourseManager();
        EnrollStudentManager enrollStudentManager = new EnrollStudentManager();

        //
        // GET: /StudentRegistration/

        public ActionResult RegisterStudent()
        {
            List<Department> aDepartments = departmentManager.ViewDepartment();
            ViewBag.Departmentlist = aDepartments;
            return View();
        }
        [HttpPost]
        public ActionResult RegisterStudent(RegisterStudent registerStudent)
        {
            List<Department> aDepartments = departmentManager.ViewDepartment();
            ViewBag.Departmentlist = aDepartments;
            string departmentCode = departmentManager.GetDepartmentCodeByID(registerStudent.DepartmentId);
            registerStudent.Code = departmentCode;

            string regno = departmentCode + "-";
            regno += registerStudent.Date.Year.ToString();
            regno += "-";
            int regNoId = registrationManager.GetRowCount(regno);
            //string s = (regNoId + 1).ToString("000");
            if (regNoId == 0)
            {
                regno += "00" + 1;
            }
            else
            {
                if (regNoId >= 1 && regNoId <= 9)
                {
                    int temp = regNoId + 1;
                    regno += "00" + temp;
                }
                else if (regNoId >= 10 && regNoId <= 99)
                {
                    int temp = regNoId + 1;
                    regno += "0" + temp;

                }
                else
                {
                    regno += "" + regNoId + 1;

                }
            }
            registerStudent.Registration_Number = regno;


            if (registrationManager.IsEmailExist(registerStudent.Email))
            {
                ViewBag.ErrorMessage = "Email already Exists";
            }
            else
            {
                int rowsAffected = registrationManager.SaveStudent(registerStudent);

                if (rowsAffected > 0)
                {
                    ViewBag.SuccessMessage = "Student inserted Successfully";
                }
                else
                {
                    ViewBag.ErrorMessage = "Insert Failed";
                }
            }
            return View();
        }

        public ActionResult EnrollStudent()
        {
            ViewBag.StudentList = registrationManager.GetAllStudent();
            ViewBag.DepartmentList = departmentManager.ViewDepartment();
            ViewBag.CourseList = courseManager.GetAllCourses();
            return View();
        }
        [HttpPost]
        public ActionResult EnrollStudent(EnrollStudent enrollStudent)
        {
            ViewBag.StudentList = registrationManager.GetAllStudent();
            ViewBag.DepartmentList = departmentManager.ViewDepartment();
            ViewBag.CourseList = courseManager.GetAllCourses();


            var courselist = enrollStudentManager.GetAllEnrollsById(enrollStudent.StudentId);
            var isExists = courselist.FirstOrDefault(a => a.CourseId == enrollStudent.CourseId);

            if (enrollStudent.CourseId == 0)
            {
                ViewBag.message = "Select Course";
            }
            else
            {
                if (isExists != null)
                {
                    ViewBag.message = "This Course Already Assigned";
                }
                else
                {
                    enrollStudentManager.SaveEnrollCourse(enrollStudent);
                    ViewBag.message = "Course Enrolled Successfully";
                }
            }
      
            return View();
        }
        public JsonResult GetStudentInfoByStudentId(int studentId)
        {
            var student = registrationManager.GetAllStudent();
            var StudentList = student.Where(m => m.Id == studentId).ToList();

            return Json(StudentList.Select(c => new
            {
                name = c.Name,
                email = c.Email,
                department = departmentManager.ViewDepartment().Where(x => x.Id == c.DepartmentId).Select(x => x.Name).Single()
            }), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCoursesByStudentId(int studentId)
        {
            var student = registrationManager.GetAllStudent().Find(m => m.Id == studentId);
            var courses = courseManager.GetAllCourses().Where(c => c.DepartmentId == student.DepartmentId);
            return Json(new SelectList(courses, "Id", "Name"));
        }


    }
}

UniversityCoursesAndResultApp/Views/StudentRegistration/EnrollStudent.cshtml
@using System.Web.UI.WebControls
@using UniversityCoursesAndResultApp.Models
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EnrollStudent</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
      <style>
        label.error {
            color: red;
        }
         #home-bar {
            height: 60px;
            width: 100%;
            background-color: darkcyan;
        }
    </style>
</head>
<body>
<div id="home-bar">
    <h3 class="text-center" style="padding-top: 15px"><a onclick=" window.location.href = '@Url.Action("Index", "Home")' " style="color: wheat" >Home</a></h3>
</div>
<div>
    <form id="enrollForm" method="POST">
        @Html.AntiForgeryToken()

        <div class="form-group" align="center">
            <table class="dataTables_sizing">
                <tr>
                    <td><label for="StudentId">Student Reg. No.</label></td>
                    <td>
                        <select id="StudentId" name="StudentId">
                            <option value="">Pls select a Registration name</option>
                            @foreach (RegisterStudent aStudent in ViewBag.StudentList)
                            {
                                <option value="@aStudent.Id">@aStudent.Registration_Number</option>
                            }

                        </select>
                    </td>
                </tr>
                <tr>
                    <td><label for="StudentName">Name</label></td>
                    <td><input type="text" class="disabled" readonly="readonly" id="StudentName" name="StudentName"/></td>
                </tr>
                <tr>
                    <td><label for="StudentEmail">Email</label></td>
                    <td><input type="text" class="disabled" readonly="readonly" id="StudentEmail" name="StudentEmail"/></td>
                </tr>
                <tr>
                    <td><label for="DepartmentId">Department</label></td>

                    <td><input type="text" class="disabled" readonly="readonly" id="DepartmentId" name="DepartmentId"/></td>

                    @*<td><input id="Code" name="DepartmentId" type="text" readonly="readonly" /></td>*@
                </tr>
                <tr>
                    <td><label for="CourseId">Select Course</label></td>
                    <td>
                        <select id="CourseId" name="CourseId"></select>
                    </td>
                </tr>
                <tr>
                    <td><label for="EnrollDate">Date</label></td>
                    <td>
                        <div class="input-group date" data-provide="datepicker">
                            <input type="date" id="EnrollDate" name="EnrollDate" class="form-control"/>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Enroll" class="btn btn-danger"/>
                    </td>
                </tr>
            </table>
        </div>
    </form>

    <div>
        @if (ViewBag.message != null)
        {
            <p style="color: green">@ViewBag.message</p>
        }
    </div>

    <script src="~/Scripts/jquery-3.1.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>

        $("#enrollForm").validate({
            rules: {
                StudentId: {
                    required: true
                },
                StudentName: { required: true },
                StudentEmail: { required: true },
                Code: { required: true },
                CourseId: { required: true },
                EnrollDate: { required: true }
            },
            messages: {
                StudentId: {
                    required: "Please select a Department"
                },
                StudentName: "",
                StudentEmail: "",
                Code: "",
                CourseId: "Please select a Course",
                EnrollDate: "Please enter a date"
            }
        });
        $(document).ready(function() {
            $("#StudentId").change(function() {
                $("#StudentName").val('');
                $("#StudentEmail").val('');
                $("#DepartmentId").val('');
                var stdntId = $("#StudentId").val();
                var json = { studentId: stdntId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentInfoByStudentId", "StudentRegistration")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {
                        //alert(value.DepartmentId);
                        $.each(data, function(key, value) {

                            //alert(key);
                            $("#StudentName").val(value.name);
                            $("#StudentEmail").val(value.email);
                            $("#DepartmentId").val(value.department);

                        });
                    }
                });
            });
            $("#StudentId").change(function() {
                var stdntId = $("#StudentId").val();
                $("#CourseId").empty();

                var json = { studentId: stdntId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCoursesByStudentId", "StudentRegistration")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    datatype: 'json',
                    success: function(data) {
                        $("#CourseId").append('<option value="">--Select Course-- </option>');
                        $.each(data, function(key, value) {
                            $("#CourseId").append('<option value=' + value.Value + '>' + value.Text + '</option>');
                        });
                    }
                });
            });
        });
    </script>
</div>
</body>
</html>

UniversityCoursesAndResultApp/Views/StudentRegistration/RegisterStudent.cshtml
@using UniversityCoursesAndResultApp.Models
@{
    Layout = null;
    List<Department> departmentList = ViewBag.Departmentlist;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RegisterStudent</title>
    <link href="/Content/style.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <style>
        label.error {
            color: red;
        }
          #home-bar {
            height: 60px;
            width: 100%;
            background-color: darkcyan;
        }
    </style>
    
    
</head>
<body>
<div id="home-bar">
    <h3 class="text-center" style="padding-top: 15px"><a onclick=" window.location.href = '@Url.Action("Index", "Home")' " style="color: wheat" >Home</a></h3>
</div>
<div>
    <fieldset>
        <legend>Register a Student</legend>
        <form id="RegisterStudentForm" method="POST">
            <div align="center">
                <table class="form-horizontal">
                    <tr>
                        <td><label for="Name"></label>Name</td>
                        <td><input type="text" name="Name" id="Name"/></td>
                    </tr>
                    <tr>
                        <td><label for="Email">Email</label></td>
                        <td><input type="text" name="Email" id="Email"/></td>
                    </tr>
                    <tr>
                        <td><label for="Contactno">Contact no</label></td>
                        <td><input type="text" name="Contactno" id="Contactno"/></td>
                    </tr>
                    <tr>
                        <td><label for="datepicker-example1"></label>Date</td>
                        <td><input type="date" id="datepicker-example1" name="Date"/></td>
                    </tr>
                    <tr>
                        <td><label for="Address">Address</label></td>
                        <td><textarea id="Address" name="Address" rows="3" cols="19"></textarea></td>
                    </tr>
                    <tr>
                        <td><label for="DepartmentId">Depetment</label></td>
                        <td>
                            <select name="DepartmentId" id="DepartmentId">
                                <option value="">Pls select Your Deparment</option>
                                @foreach (Department aDepartment in departmentList)
                                {
                                    <option value="@aDepartment.Id">@aDepartment.Name</option>
                                }
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" name="submit" value="Register" class="btn btn-danger"/></td>
                    </tr>
                </table>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <label class="text-danger" style="color: red">@ViewBag.ErrorMessage</label>
                    <label class="text-success" style="color: green">@ViewBag.SuccessMessage</label>
                </div>
            </div>

        </form>
    </fieldset>

</div>


<script src="~/Scripts/bootstrap-datepicker.js"></script>
<script src="~/Scripts/jquery-3.1.0.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>

<script>
    $(document).ready(function() {
        var currentDate = new Date();
        $('#datepicker-example1').datepicker({
            appendText: 'yyyy-mm-dd',
            inline: true,
            showOtherMonths: true,
            dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],


        });
        $('#datepicker-example1').datepicker("setDate", currentDate);

    });
    $("#RegisterStudentForm").validate({
        rules: {
            Name: {
                required: true
            },
            Email: {
                required: true,
                email: true
            },
            Contactno: {
                required: true,
                number: true,
                minlength: 11
            },
            Address: {
                required: true
            },
            DepartmentId: {
                required: true
            }
        },
        messages: {
            Name: {
                required: "Please enter Student name"
            },
            Email: {
                required: "Please enter Student email",
                email: "Please enter a valid email"
            },
            Contactno: {
                required: "Please enter Student Contact number",
                number: "Contact number must be in number format",
                minlength: "Contact number must contain at least 11 digits"
            },
            Address: {
                required: "Please enter Student address"
            },
            DepartmentId: {
                required: "Please select a department"
            }
        }
    });


</script>

</body>
</html>